### ISSUE TITLE
Nice, but there is a bug

### ISSUE THREAD

**Issue by AlphaYe** [karakanb/unblock-me-solver#1]
Look at Step 4 and Step 5 below, it can not be done in one step :
Step 4

0 0 0 0 0 0
0 0 0 0 0 0
2 1 1 6 7 0
2 4 0 6 7 0
3 4 0 6 0 0
3 5 5 0 0 0

===========================
===========================

Step 5

0 0 0 0 7 0
0 0 0 0 7 0
2 1 1 0 0 0
2 4 0 6 0 0
3 4 0 6 0 0
3 5 5 6 0 0

Bug Fix:
Modify this function
Board Solver::createMovedInstance(Board board, int blockIndex, int direction) {
    Board tempBoard;
    tempBoard = board;

    // Set the identifier to a random number while setting the referrer to the previous board's identifier.
   // tempBoard.identifier = board.getHash();  // this line cause bug
    tempBoard.referrer = board.identifier;

    // Move the block
    tempBoard.moveBlock(blockIndex, direction);

    tempBoard.referrer = tempBoard.getHash();  // that is ok okokok
    return tempBoard;
}

sorry for my poor english

**Comment by karakanb** [comment]
Thank you very much for the issue. It has been a long time since I have written the code for this project; I will take a look at it and fix the bug. Also, if you would like to submit a pull request, I would be glad to merge it. Thanks a lot for the information.

**Comment by tbeu** [comment]
Addressed by #2.
