### ISSUE TITLE
Dead link to screenshot

### ISSUE THREAD

**Issue by tbeu** [karakanb/unblock-me-solver#4]
`http://logonubul.com/images/unblock-me.png` as referenced by the README.md is a dead link.

**Comment by karakanb** [comment]
I think it was an image like this one:
![image](https://user-images.githubusercontent.com/16530606/147769754-4eb7f159-280e-4ecd-8ccb-9930a2637bc3.png)

Feel free to create a PR with a working link, or upload one with the repository.
